services:
  sallybook-web:
    container_name: sallybook-web
    build: ./sallybook-web
    ports:
      - 3001:3001
    env_file:
      - ./.env
    networks:
      - sallybook
  sallybook-api:
    container_name: sallybook-api
    build: ./sallybook-api
    env_file:
      - ./.env
    networks:
      - newtone
networks:
  newtone:
    external: true
